spring:
  application:
    name: lumos-api-service
  datasource:
    url: jdbc:postgresql://localhost:5432/lumos
    username: ${DB_USERNAME:giapnt}
    password: ${DB_PASSWORD:abcd1234}
    hikari:
      schema: lumos
  jpa:
    properties:
      hibernate:
        default_schema: lumos
  flyway:
    default-schema: lumos
    schemas:
      - lumos
    create-schemas: true
  messages:
    basename: messages
    encoding: UTF-8

app:
  cors:
    allowed-origins:
      - http://localhost:3000
      - http://localhost:5173
    allowed-methods:
      - GET
      - POST
      - PUT
      - PATCH
      - DELETE
      - OPTIONS
    allowed-headers:
      - "*"
    exposed-headers:
      - Location
    allow-credentials: true
    max-age-seconds: 3600
